---
trust-domain: "ap"
task-priority: low

taskgraph:
  cached-task-prefix: "ap.v2.scriptworkers"
  repositories:
    scriptworkers:
      name: "scriptworkers"

  register: eije_taskgraph:register

workers:
  aliases: {}
